services:
  freightapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080"
    volumes:
      - ./FreightAPI:/app/src
    command: dotnet watch run --urls "http://+:8080"
